version: "3.8"
services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: unless-stopped
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      SIGNUPS_ALLOWED: false
    volumes:
      - ${DOCKERCONFDIR}/vaultwarden/data/:/data/
    labels:
      - swag=enable
      - swag_auth=authelia
    ports:
      - 80:80
    networks:
      - shyDockerServer

networks:
  shyDockerServer:
    driver: bridge
    external: true
