version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - generalStackNetwork

x-authelia-conf: &authelia
  labels:
    - swag=enable
    - swag_auth=authelia

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      <<: *environment
      DEFAULT_WORKSPACE: /config/workspace
    <<: [ *default_conf, *authelia ]
    volumes:
      - ${DOCKERCONFDIR}/code-server:/config
    ports:
      - 8443:8443

networks:
  generalStackNetwork:
    driver: bridge