version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - generalStackNetwork

services:
  firefly_iii_app:
    image: fireflyiii/core:latest
    hostname: firefly_iii_app
    container_name: firefly_iii_app
    environment:
      TZ: ${TZ}
      APP_ENV: "local"
      APP_DEBUG: false
      SITE_OWNER: ${DEFAULT_EMAIL}
      APP_KEY: ${FIREFLY3_APP_KEY}
      DEFAULT_LANGUAGE: "en_US"
      DEFAULT_LOCALE: "equal"
      TRUSTED_PROXIES: "**"
      LOG_CHANNEL: "stack"
      APP_LOG_LEVEL: "notice"
      AUDIT_LOG_LEVEL: "info"
      DB_CONNECTION: "mysql"
      DB_HOST: "firefly_iii_db"
      DB_PORT: "3306"
      DB_DATABASE: "firefly"
      DB_USERNAME: "firefly"
      DB_PASSWORD: ${FIREFLY3_DB_PWD}
      CACHE_DRIVER: "file"
      SESSION_DRIVER: "file"
      COOKIE_PATH: "/"
      COOKIE_SECURE: false
      COOKIE_SAMESITE: "lax"
      SEND_ERROR_MESSAGE: true
      SEND_REPORT_JOURNALS: false
      ENABLE_EXTERNAL_MAP: false
      ENABLE_EXTERNAL_RATES: false
      MAP_DEFAULT_LAT: "51.983333"
      MAP_DEFAULT_LONG: "5.916667"
      MAP_DEFAULT_ZOOM: "6"
      AUTHENTICATION_GUARD: "web"
      DISABLE_FRAME_HEADER: false
      DISABLE_CSP_HEADER: false
      ALLOW_WEBHOOKS: false
      STATIC_CRON_TOKEN: ${FIREFLY3_APP_KEY}
      DKR_BUILD_LOCALE: false
      DKR_CHECK_SQLITE: true
      DKR_RUN_MIGRATION: true
      DKR_RUN_UPGRADE: true
      DKR_RUN_VERIFY: true
      DKR_RUN_REPORT: true
      DKR_RUN_PASSPORT_INSTALL: true
      APP_NAME: "FireflyIII"
      BROADCAST_DRIVER: "log"
      QUEUE_DRIVER: "sync"
      CACHE_PREFIX: "firefly"
      FIREFLY_III_LAYOUT: "v1"
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/firefly_iii/firefly_iii_upload/:/var/www/html/storage/upload
    depends_on:
      - firefly_iii_db

  firefly_iii_db:
    image: lscr.io/linuxserver/mariadb
    hostname: firefly_iii_db
    container_name: firefly_iii_db
    environment:
      TZ: ${TZ}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: "firefly"
      MYSQL_PASSWORD: ${FIREFLY3_DB_PWD}
      MYSQL_DATABASE: "firefly"
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/firefly_iii/firefly_iii_db/:/var/lib/mysql

  firefly_iii_cron:
    image: alpine
    container_name: firefly_iii_cron
    environment:
      TZ: ${TZ}
    <<: *default_conf
    command: sh -c "echo \"0 3 * * * wget -qO- http://firefly_iii_app:8085/api/v1/cron/${FIREFLY3_APP_KEY}\" | crontab - && crond -f -L /dev/stdout" 

networks:
  generalStackNetwork:
    driver: bridge
    external: true
