version: "3.3"

services:
  app:
    image: fireflyiii/core:latest
    hostname: app
    container_name: firefly_iii_core
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      TZ: ${TZ}
      APP_ENV: "local"
      APP_DEBUG: false
      SITE_OWNER: ${DEFAULT_EMAIL}
      APP_KEY: ${FIREFLY3_APP_KEY}
      DEFAULT_LANGUAGE: "en_US"
      DEFAULT_LOCALE: "equal"
      TRUSTED_PROXIES: "**"
      LOG_CHANNEL: "stack"
      APP_LOG_LEVEL: "notice"
      AUDIT_LOG_LEVEL: "info"
      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_DATABASE: "firefly"
      DB_USERNAME: "firefly"
      DB_PASSWORD: ${FIREFLY3_DB_PWD}
      CACHE_DRIVER: "file"
      SESSION_DRIVER: "file"
      COOKIE_PATH: "/"
      COOKIE_SECURE: false
      COOKIE_SAMESITE: "lax"
      SEND_ERROR_MESSAGE: true
      SEND_REPORT_JOURNALS: false
      ENABLE_EXTERNAL_MAP: false
      ENABLE_EXTERNAL_RATES: false
      MAP_DEFAULT_LAT: "51.983333"
      MAP_DEFAULT_LONG: "5.916667"
      MAP_DEFAULT_ZOOM: "6"
      AUTHENTICATION_GUARD: "web"
      DISABLE_FRAME_HEADER: false
      DISABLE_CSP_HEADER: false
      ALLOW_WEBHOOKS: false
      STATIC_CRON_TOKEN: ${FIREFLY3_APP_KEY}
      DKR_BUILD_LOCALE: false
      DKR_CHECK_SQLITE: true
      DKR_RUN_MIGRATION: true
      DKR_RUN_UPGRADE: true
      DKR_RUN_VERIFY: true
      DKR_RUN_REPORT: true
      DKR_RUN_PASSPORT_INSTALL: true
      APP_NAME: "FireflyIII"
      BROADCAST_DRIVER: "log"
      QUEUE_DRIVER: "sync"
      CACHE_PREFIX: "firefly"
      FIREFLY_III_LAYOUT: "v1"
    volumes:
      - ${DOCKERCONFDIR}/firefly_iii/firefly_iii_upload:/var/www/html/storage/upload
    networks:
      - shyDockerServer
    ports:
      - 8085:8080
    depends_on:
      - db

  db:
    image: mariadb
    hostname: db
    container_name: firefly_iii_db
    user: "${PUID}:${PGID}"
    environment:
      TZ: ${TZ}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: "firefly"
      MYSQL_PASSWORD: ${FIREFLY3_DB_PWD}
      MYSQL_DATABASE: "firefly"
    restart: unless-stopped
    networks:
      - shyDockerServer
    volumes:
      - ${DOCKERCONFDIR}/firefly_iii/firefly_iii_db:/var/lib/mysql

  cron:
    image: alpine
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    environment:
      TZ: ${TZ}
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/${FIREFLY3_APP_KEY}\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - shyDockerServer

networks:
  shyDockerServer:
    driver: bridge
    external: true
