version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - generalStackNetwork

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  gaseous-server:
    container_name: gaseous-server
    image: gaseousgames/gaseousserver:latest
    user: ${PUID}:{PGID}
    environment:
      <<: *environment
      dbhost: gaseous_db
      dbuser: root
      dbpass: ${GASEOUS_DB_ROOT_PASSWORD}
      igdbclientid: ${ROMM_IGDB_CLIENTID}
      igdbclientsecret: ${ROMM_IGDB_CLIENTPASSWORD}
    <<: *default_conf
    depends_on:
      - gaseous_db
    labels:
      - docker-volume-backup.stop-during-backup=true
    ports:
      - 5198:80
    volumes:
      - ${DOCKERCONFDIR}/gaseous/gaseous_data:/root/.gaseous-server
      - /smb/library:/library:ro

  gaseous_db:
    image: lscr.io/linuxserver/mariadb
    container_name: gaseous_db
    hostname: gaseous_db
    environment:
      <<: *environment
      MARIADB_ROOT_PASSWORD: ${GASEOUS_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: gaseous
      MYSQL_USER: gaseous
      MYSQL_PASSWORD: ${GASEOUS_DB_PASSWORD}
    <<: *default_conf
    labels:
      - docker-volume-backup.archive-pre=/bin/sh -c 'rm -rf /tmp/gaseous_db-dump* && mysqldump --all-databases > /tmp/gaseous_db-dump-$(date +"%Y_%m_%d-%I_%M_%p").sql'
    volumes:
      - ${DOCKERCONFDIR}/gaseous/gaseous_db_data:/var/lib/mysql
      - ${DOCKERCONFDIR}/gaseous/gaseous_db_data/backups:/tmp
      - ${DOCKERCONFDIR}/gaseous/gaseous_db_data/.my.cnf:/root/.my.cnf

networks:
  generalStackNetwork:
    driver: bridge
    external: true
