version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - guacamoleStackNetwork

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  guacd:
    container_name: guacd
    image: guacamole/guacd
    <<: *default_conf
    # ports 4822

  guacamole:
    container_name: guacamole
    image: guacamole/guacamole
    depends_on:
      - guacd
      - guacamole_db
    environment:
      <<: *environment
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: guacamole_db
      MYSQL_DATABASE: guacamole_db
      MYSQL_PASSWORD: ${GUACAMOLE_DB_PASSWORD}
      MYSQL_USER: guacamole
      MYSQL_DRIVER: mysql
      MYSQL_SSL_MODE: disabled
    <<: *default_conf
    labels:
      - swag=enable
      - swag_auth=authelia
    ports:
      - 8080:8080

  guacamole_db:
    image: lscr.io/linuxserver/mariadb
    container_name: guacamole_db
    environment:
      <<: *environment
      MYSQL_ROOT_PASSWORD: ${GUACAMOLE_DB_PASSWORD}
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole
      MYSQL_PASSWORD: ${GUACAMOLE_DB_PASSWORD}
    <<: *default_conf
    volumes:
      - guacamole_db:/config

volumes:
  guacamole_db:
    name: guacamole_db
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/guacamole/guacamole_db

networks:
  guacamoleStackNetwork:
    driver: bridge
    external: true
