version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - swagStackNetwork

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      <<: *environment
      SERVERURL: ${DUCKDNS_SUBDOMAIN}
      SERVERPORT: 51820
      PEERS: phone,steamdeck
      PEERDNS: 1.1.1.1, 8.8.8.8, 8.8.4.4
    volumes:
      - ${DOCKERCONFDIR}/wireguard:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - swagStackNetwork
      - managementStackNetwork
      - arrStackNetwork
      - downloadStackNetwork
      - generalStackNetwork
      - socketProxyNetwork
      - guacamoleStackNetwork

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      <<: *environment
      SUBDOMAINS: ${DUCKDNS_SUBDOMAIN}
      TOKEN: ${DUCKDNS_TOKEN}
    <<: *default_conf

  swag_duckdns:
    image: lscr.io/linuxserver/swag
    container_name: swag_duckdns
    cap_add:
      - NET_ADMIN
    environment:
      <<: *environment
      DOCKER_MODS: linuxserver/mods:universal-docker|linuxserver/mods:swag-crowdsec
      CROWDSEC_API_KEY: ${SWAG_CROWDSEC_API_KEY}
      CROWDSEC_LAPI_URL: http://crowdsec:8080
      URL: ${DUCKDNS_SUBDOMAIN}
      SUBDOMAINS: wildcard
      VALIDATION: duckdns
      DUCKDNSTOKEN: ${DUCKDNS_TOKEN}
    <<: *default_conf
    volumes:
      - swag_duckdns:/config

volumes:
  swag_duckdns:
    name: swag_duckdns
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/swag_duckdns
  wireguard:
    name: wireguard
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/wireguard

networks:
  swagStackNetwork:
    driver: bridge
    external: true
  managementStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
  downloadStackNetwork:
    driver: bridge
    external: true
  generalStackNetwork:
    driver: bridge
    external: true
  socketProxyNetwork:
    driver: bridge
    external: true
  guacamoleStackNetwork:
    driver: bridge
    external: true
