version: "3.8"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      SERVERURL: auto
      SERVERPORT: 51820
      PEERS: peer1test
      PEERDNS: auto
    volumes:
      - ${DOCKERCONFDIR}/wireguard:/config
      - ${DOCKERCONFDIR}/wireguard/etc/wireguard:/etc/wireguard
      - /lib/modules:/lib/modules
    ports:
      - 5000:5000
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - swagStackNetwork
      - managementStackNetwork
      - arrStackNetwork
      - downloadStackNetwork
      - generalStackNetwork

  wireguard-ui:
    build: .
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    user: "${PUID}:${PGID}"
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      SESSION_SECRET: ${WGUI_SESSION_SECRET}
      WGUI_USERNAME: shyonae
      WGUI_PASSWORD: ${WGUI_PASSWORD}
      #WG_CONF_TEMPLATE: "/etc/wireguard/wg0.conf"
      WGUI_MANAGE_START: false
      WGUI_MANAGE_RESTART: true
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - ${DOCKERCONFDIR}/wireguard-ui/db:/app/db
      - ${DOCKERCONFDIR}/wireguard/etc/wireguard:/etc/wireguard
    networks:
      - generalStackNetwork

networks:
  swagStackNetwork:
    driver: bridge
    external: true
  managementStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
  downloadStackNetwork:
    driver: bridge
    external: true
  generalStackNetwork:
    driver: bridge
    external: true
