version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - generalStackNetwork

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    container_name: bookstack
    environment:
      <<: *environment
      APP_URL: ${BOOKSTACK_APP_URL}
      DB_HOST: bookstack_db
      DB_PORT: 3306
      DB_USER: bookstack
      DB_PASS: ${BOOKSTACK_DB_PASSWORD}
      DB_DATABASE: bookstackapp
    <<: *default_conf
    labels:
      - swag=enable
      - swag_auth=authelia
      - docker-volume-backup.stop-during-backup=true
    volumes:
      - ${DOCKERCONFDIR}/bookstack/bookstack_app_data:/config
    depends_on:
      - bookstack_db

  bookstack_db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack_db
    environment:
      <<: *environment
      MYSQL_ROOT_PASSWORD: ${BOOKSTACK_DB_PASSWORD}
      MYSQL_DATABASE: bookstackapp
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: ${BOOKSTACK_DB_PASSWORD}
    <<: *default_conf
    labels:
      - docker-volume-backup.archive-pre=/bin/sh -c 'mysqldump --user bookstack --password=${BOOKSTACK_DB_PASSWORD} bookstackapp > /tmp/dump-$(date +"%Y_%m_%d-%I_%M_%p").sql'
    volumes:
      - ${DOCKERCONFDIR}/bookstack/bookstack_db_data:/config
      - ${DOCKERCONFDIR}/bookstack/bookstack_db_data/backups:/tmp

networks:
  generalStackNetwork:
    driver: bridge
    external: true
