version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - arrStackNetwork

x-authelia-conf: &autheliaPlusBackup
  labels:
    - swag=enable
    - swag_auth=authentik
    - docker-volume-backup.stop-during-backup=true

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      <<: *environment
    <<: [*default_conf, *autheliaPlusBackup]
    ports:
      - 6767:6767
    volumes:
      - ${DOCKERCONFDIR}/bazarr:/config
      - ${DOCKERSTORAGEDIR}:/storage

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      <<: *environment
    <<: [*default_conf, *autheliaPlusBackup]
    ports:
      - 7878:7878
    volumes:
      - ${DOCKERCONFDIR}/radarr:/config
      - ${DOCKERSTORAGEDIR}:/storage

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      <<: *environment
    <<: [*default_conf, *autheliaPlusBackup]
    ports:
      - 8989:8989
    volumes:
      - ${DOCKERCONFDIR}/sonarr:/config
      - ${DOCKERSTORAGEDIR}:/storage

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: false
      LOG_LEVEL: info
      <<: *environment
    <<: *default_conf
    ports:
      - 8191:8191

  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    environment:
      <<: *environment
    <<: [*default_conf, *autheliaPlusBackup]
    ports:
      - 5454:5454
    volumes:
      - ${DOCKERCONFDIR}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      <<: *environment
    <<: [*default_conf, *autheliaPlusBackup]
    ports:
      - 9696:9696
    volumes:
      - ${DOCKERCONFDIR}/prowlarr:/config

  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    environment:
      <<: *environment
    <<: *default_conf
    labels:
      - docker-volume-backup.stop-during-backup=true
    volumes:
      - ${DOCKERCONFDIR}/autobrr:/config
    ports:
      - 7474:7474

  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - ${DOCKERSTORAGEDIR}:/storage
    <<: *default_conf
    user: ${PUID}:${PGID}
    environment:
      - TZ=${TZ}
      # Sonarr Config
      - UN_SONARR_0_URL=http://sonarr:8989
      - UN_SONARR_0_API_KEY=${UNPACKERR_SONARR_APIKEY}
      - UN_SONARR_0_PATHS_0=/storage
      - UN_SONARR_0_PROTOCOLS=torrent
      - UN_SONARR_0_TIMEOUT=10s
      - UN_SONARR_0_DELETE_ORIG=false
      - UN_SONARR_0_DELETE_DELAY=5m
      # Radarr Config
      - UN_RADARR_0_URL=http://radarr:7878
      - UN_RADARR_0_API_KEY=${UNPACKERR_RADARR_APIKEY}
      - UN_RADARR_0_PATHS_0=/storage
      - UN_RADARR_0_PROTOCOLS=torrent
      - UN_RADARR_0_TIMEOUT=10s
      - UN_RADARR_0_DELETE_ORIG=false
      - UN_RADARR_0_DELETE_DELAY=5m
    security_opt:
      - no-new-privileges:true

networks:
  arrStackNetwork:
    driver: bridge
    external: true
