version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - arrStackNetwork

x-authelia-conf: &authelia
  labels:
    - swag=enable
    - swag_auth=authelia

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    #ports:
    #  - 6767:6767
    volumes:
      - ${DOCKERCONFDIR}/bazarr:/config
      - ${DOCKERSTORAGEDIR}:/storage

  bazarranime:
    container_name: bazarranime
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    volumes:
      - ${DOCKERCONFDIR}/bazarranime:/config
      - ${DOCKERSTORAGEDIR}:/storage

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    #ports:
    #  - 7878:7878
    volumes:
      - ${DOCKERCONFDIR}/radarr:/config
      - ${DOCKERSTORAGEDIR}:/storage

  radarranime:
    container_name: radarranime
    image: lscr.io/linuxserver/radarr:latest
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    volumes:
      - ${DOCKERCONFDIR}/radarranime:/config
      - ${DOCKERSTORAGEDIR}:/storage

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:develop
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    #ports:
    #  - 8989:8989
    volumes:
      - ${DOCKERCONFDIR}/sonarr:/config
      - ${DOCKERSTORAGEDIR}:/storage

  sonarranime:
    container_name: sonarranime
    image: lscr.io/linuxserver/sonarr:develop
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    volumes:
      - ${DOCKERCONFDIR}/sonarranime:/config
      - ${DOCKERSTORAGEDIR}:/storage

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: false
      LOG_LEVEL: info
      <<: *environment
    <<: *default_conf
    #ports:
    #  - 8191:8191

  notifiarr:
    container_name: notifiarr
    hostname: notifiarr
    image: golift/notifiarr
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    #ports:
    #  - 5454:5454
    volumes:
      - ${DOCKERCONFDIR}/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    #ports:
    #  - 9696:9696
    volumes:
      - ${DOCKERCONFDIR}/prowlarr:/config

networks:
  arrStackNetwork:
    driver: bridge
    external: true
