version: "3"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - generalStackNetwork

services:
  homechart:
    image: ghcr.io/candiddev/homechart:latest
    container_name: homechart
    depends_on:
      - homechart_db
    environment:
      HOMECHART_POSTGRESQL_HOSTNAME: homechart_db
      HOMECHART_POSTGRESQL_PASSWORD: ${HOMECHART_DB_PASSWORD}
      HOMECHART_POSTGRESQL_USERNAME: postgres
    <<: *default_conf

  homechart_db:
    image: docker.io/postgres:14
    container_name: homechart_db
    environment:
      POSTGRES_PASSWORD: ${HOMECHART_DB_PASSWORD}
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/homechart/db_data:/var/lib/postgresql/data

networks:
  generalStackNetwork:
    driver: bridge
    external: true
