services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.6.7
    container_name: qbittorrent
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      UMASK: ${UMASK}
      TZ: ${TZ}
      WEBUI_PORT: 8080
      TORRENTING_PORT: 52525
    labels:
      - swag=enable
      - swag_auth=authentik
      - docker-volume-backup.stop-during-backup=true
    networks:
      - downloadStackNetwork
      - arrStackNetwork
      - musicStackNetwork
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"
    volumes:
      - ${DOCKERCONFDIR}/qbittorrent:/config
      - ${DOCKERSTORAGEDIR}:/storage
    ports:
      - 8080:8080
      - 52525:52525
      - 52525:52525/udp
    restart: unless-stopped

networks:
  downloadStackNetwork:
    driver: bridge
    external: true
  musicStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
