x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - managementStackNetwork
    - socketProxyNetwork

x-logging-conf: &logging
  logging:
    driver: "json-file"
    options:
      max-file: "2"
      max-size: "100m"

x-authentik-conf: &labels
  labels:
    # - swag=enable
    # - swag_auth=authentik
    - docker-volume-backup.stop-during-backup=true

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}
  DOCKER_HOST: dockerproxy

services:
  ## PORTAINER##
  portainer:
    command: -H tcp://dockerproxy:2375
    container_name: portainer
    image: portainer/portainer-ce:latest
    environment:
      <<: *environment
    <<: [*default_conf, *labels, *logging]
    ports:
      - 9000:9000
    volumes:
      - ${DOCKERCONFDIR}/portainer:/data
      - ${DOCKERSTORAGEDIR}:/storage

  # ## HOMARR ##
  # homarr:
  #   container_name: homarr
  #   image: ghcr.io/ajnart/homarr:latest
  #   environment:
  #     PGID: ${PGID}
  #     PUID: ${PUID}
  #     TZ: ${TZ}
  #     DOCKER_HOST: tcp://dockerproxy:2375
  #   <<: *default_conf
  #   labels:
  #     - docker-volume-backup.stop-during-backup=true
  #   volumes:
  #     - ${DOCKERCONFDIR}/homarr/configs:/app/data/configs
  #     - ${DOCKERCONFDIR}/homarr/icons:/app/public/icons
  #     - ${DOCKERCONFDIR}/homarr/data:/data
  #   ports:
  #     - 7575:7575

  # ## UPTIME KUMA ##
  # uptime-kuma:
  #   image: louislam/uptime-kuma
  #   container_name: uptime-kuma
  #   environment:
  #     <<: *environment
  #   <<: *default_conf
  #   volumes:
  #     - ${DOCKERCONFDIR}/uptime-kuma:/app/data
  #   labels:
  #     - docker-volume-backup.stop-during-backup=true
  #   ports:
  #     - 3001:3001

  # ## WHATSUPDOCKER ##
  # whatsupdocker:
  #   image: fmartinou/whats-up-docker
  #   container_name: whatsupdocker
  #   environment:
  #     <<: *environment
  #     DOCKER_HOST: tcp://dockerproxy:2375
  #     WUD_AUTH_OIDC_AUTHENTIK_CLIENTID: ${WUD_AUTH_OIDC_AUTHENTIK_CLIENTID}
  #     WUD_AUTH_OIDC_AUTHENTIK_CLIENTSECRET: ${WUD_AUTH_OIDC_AUTHENTIK_CLIENTSECRET}
  #     WUD_AUTH_OIDC_AUTHENTIK_DISCOVERY: ${WUD_AUTH_OIDC_AUTHENTIK_DISCOVERY}
  #     WUD_AUTH_OIDC_AUTHENTIK_REDIRECT: true
  #   <<: *default_conf
  #   volumes:
  #     - ${DOCKERCONFDIR}/whatsupdocker:/store
  #   labels:
  #     - docker-volume-backup.stop-during-backup=true
  #   ports:
  #     - 3043:3000

  ## DOZZLE ##
  # dozzle:
  #   container_name: dozzle
  #   image: amir20/dozzle:latest
  #   environment:
  #     DOZZLE_REMOTE_HOST: tcp://dockerproxy:2375
  #     <<: *environment
  #   <<: *default_conf
  #   ports:
  #     - 9999:8080

  ## DOCKING STATION ##
  docking-station:
    image: loolzzz/docking-station:latest
    container_name: docking-station
    environment:
      <<: *environment
      WEB_PORT: 3046
    <<: [*default_conf, *labels, *logging]
    volumes:
      - ${DOCKERCONFDIR}/docking-station/config:/config
      - ${DOCKERCONFDIR}/docking-station/data:/data
      - ${DOCKERCONFDIR}/docking-station/logs:/logs
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_COMPOSE_DIR}:${DOCKER_COMPOSE_DIR}
    ports:
      - 3046:3046

  ## DOCKER VOLUME BACKUP ##
  docker-volume-backup:
    image: offen/docker-volume-backup:latest
    container_name: docker-volume-backup
    user: 0:100
    environment:
      BACKUP_CRON_EXPRESSION: "30 06 * * *"
      BACKUP_COMPRESSION: "gz"
      GZIP_PARALLELISM: 1
      BACKUP_FILENAME: backup-%Y-%m-%dT%H-%M-%S.tar.gz
      BACKUP_LATEST_SYMLINK: backup-latest.tar.gz
      BACKUP_SKIP_BACKENDS_FROM_PRUNE: s3,webdav,ssh,azure,dropbox
      BACKUP_ARCHIVE: "/archive"
      BACKUP_RETENTION_DAYS: "7"
      BACKUP_PRUNING_LEEWAY: "1m"
      BACKUP_PRUNING_PREFIX: "backup-"
      EXEC_FORWARD_OUTPUT: "false"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "2"
        max-size: "100m"
    networks:
      - managementStackNetwork
      - socketProxyNetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKERCONFDIR}:/backup:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /nfs/backups/docker-volumes-backups:/archive:rw

networks:
  managementStackNetwork:
    driver: bridge
    external: true
  socketProxyNetwork:
    driver: bridge
    external: true
