version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - managementStackNetwork
    - socketProxyNetwork

x-authelia-conf: &authelia
  labels:
    - swag=enable
    - swag_auth=authelia

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}
  DOCKER_HOST: dockerproxy

services:
  portainer:
    command: -H tcp://dockerproxy:2375
    container_name: portainer
    image: portainer/portainer-ce:latest
    user: "${PUID}:${PGID}"
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    ports:
      - 9000:9000
    volumes:
      - portainer:/data
      - ${DOCKERSTORAGEDIR}:/storage

  # watchtower:
  #   image: containrrr/watchtower
  #   container_name: watchtower
  #   environment:
  #     <<: *environment
  #     DOCKER_HOST: "tcp://dockerproxy:2375"
  #     WATCHTOWER_NOTIFICATION_URL: ${WATCHTOWER_MAIL_URL}
  #     WATCHTOWER_SCHEDULE: "0 0 03 * * *"
  #     WATCHTOWER_CLEANUP: "true"
  #   <<: *default_conf

  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    environment:
      <<: *environment
    <<: *default_conf
    volumes:
      - homarr:/app
    ports:
      - 7575:7575

  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    volumes:
      - uptime-kuma:/app/data
    ports:
      - 3001:3001

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    environment:
      DOZZLE_REMOTE_HOST: tcp://dockerproxy:2375
      <<: *environment
    <<: [*default_conf, *authelia]
    ports:
      - 9999:8080

  # duplicati:
  #   image: lscr.io/linuxserver/duplicati:latest
  #   container_name: duplicati
  #   environment:
  #     UMASK: ${UMASK}
  #     <<: *environment
  #   <<: [*default_conf, *authelia]
  #   volumes:
  #     - ${DOCKERCONFDIR}/duplicati/config:/config
  #     - /var/local/duplicati/backups:/backups
  #     - ${DOCKERCONFDIR}:/source
  #   ports:
  #     - 8200:8200

  # cosmos-server:
  #   image: azukaar/cosmos-server:latest
  #   container_name: cosmos-server
  #   hostname: cosmos-server
  #   environment:
  #     DOCKER_HOST: tcp://dockerproxy:2375
  #     CLOUDFLARE_EMAIL: ${DEFAULT_EMAIL}
  #     CLOUDFLARE_API_KEY: ${SWAG_CF_API_TOKEN}
  #     <<: *environment
  #   <<: *default_conf
  #   volumes:
  #     - ${DOCKERCONFDIR}/cosmos-server:/config
  #     - ${DOCKERCONFDIR}:/mnt/host/appdata
  #     - ${DOCKERSTORAGEDIR}:/mnt/host/storage
  #   ports:
  #     - "8067:80"
  #     - "4453:443"
  #     - "4242:4242/udp"

volumes:
  homarr:
    name: homarr
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/homarr
  portainer:
    name: portainer
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/portainer
  uptime-kuma:
    name: uptime-kuma
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/uptime-kuma

networks:
  managementStackNetwork:
    driver: bridge
    external: true
  socketProxyNetwork:
    driver: bridge
    external: true
