services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      HOMEPAGE_VAR_ADGUARD_USERNAME: ${HOMEPAGE_VAR_ADGUARD_USERNAME}
      HOMEPAGE_VAR_ADGUARD_PASSWORD: ${HOMEPAGE_VAR_ADGUARD_PASSWORD}
      HOMEPAGE_VAR_OPEN_WEATHER_MAP_API_KEY: ${HOMEPAGE_VAR_OPEN_WEATHER_MAP_API_KEY}
      HOMEPAGE_VAR_PROXMOX_USERNAME: ${HOMEPAGE_VAR_PROXMOX_USERNAME}
      HOMEPAGE_VAR_PROXMOX_PASSWORD: ${HOMEPAGE_VAR_PROXMOX_PASSWORD}
      HOMEPAGE_VAR_PBS_USERNAME: ${HOMEPAGE_VAR_PBS_USERNAME}
      HOMEPAGE_VAR_PBS_PASSWORD: ${HOMEPAGE_VAR_PBS_PASSWORD}
      HOMEPAGE_VAR_OVM_USERNAME: ${HOMEPAGE_VAR_OVM_USERNAME}
      HOMEPAGE_VAR_OVM_PASSWORD: ${HOMEPAGE_VAR_OVM_PASSWORD}
      HOMEPAGE_VAR_NAVIDROME_TOKEN: ${HOMEPAGE_VAR_NAVIDROME_TOKEN}
      HOMEPAGE_VAR_NAVIDROME_SALT: ${HOMEPAGE_VAR_NAVIDROME_SALT}
      HOMEPAGE_VAR_LINKWARDEN_TOKEN: ${HOMEPAGE_VAR_LINKWARDEN_TOKEN}
      HOMEPAGE_VAR_QBITTORRENT_PWD: ${HOMEPAGE_VAR_QBITTORRENT_PWD}
      HOMEPAGE_VAR_BAZARR_KEY: ${HOMEPAGE_VAR_BAZARR_KEY}
      HOMEPAGE_VAR_RADARR_KEY: ${HOMEPAGE_VAR_RADARR_KEY}
      HOMEPAGE_VAR_SONARR_KEY: ${HOMEPAGE_VAR_SONARR_KEY}
      HOMEPAGE_VAR_PROWLARR_KEY: ${HOMEPAGE_VAR_PROWLARR_KEY}
      HOMEPAGE_VAR_JELLYFIN_KEY: ${HOMEPAGE_VAR_JELLYFIN_KEY}
      HOMEPAGE_VAR_JELLYSEER_KEY: ${HOMEPAGE_VAR_JELLYSEER_KEY}
      HOMEPAGE_VAR_READARR_KEY: ${HOMEPAGE_VAR_READARR_KEY}
      HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY: ${HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY}
      HOMEPAGE_VAR_IMMICH_TOKEN: ${HOMEPAGE_VAR_IMMICH_TOKEN}
      HOMEPAGE_VAR_ROMM_USER: ${HOMEPAGE_VAR_ROMM_USER}
      HOMEPAGE_VAR_ROMM_PWD: ${HOMEPAGE_VAR_ROMM_PWD}
      HOMEPAGE_VAR_HOMEBOX_USER: ${HOMEPAGE_VAR_HOMEBOX_USER}
      HOMEPAGE_VAR_HOMEBOX_PWD: ${HOMEPAGE_VAR_HOMEBOX_PWD}
    ports:
      - 3045:3000
    volumes:
      - ./config/docker.yaml:/app/config/docker.yaml
      - ./config/widgets.yaml:/app/config/widgets.yaml
      - ./config/settings.yaml:/app/config/settings.yaml
      - ./config/services.yaml:/app/config/services.yaml
      - ./images:/app/public/images
      - ${DOCKERCONFDIR}/homepage/config:/app/config 
    networks:
      - swagStackNetwork
      - musicStackNetwork
      - managementStackNetwork
      - arrStackNetwork
      - downloadStackNetwork
      - generalStackNetwork
      - socketProxyNetwork
      - guacamoleStackNetwork
      - immichStackNetwork
    labels:
      - docker-volume-backup.stop-during-backup=true

networks:
  swagStackNetwork:
    driver: bridge
    external: true
  musicStackNetwork:
    driver: bridge
    external: true
  managementStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
  downloadStackNetwork:
    driver: bridge
    external: true
  generalStackNetwork:
    driver: bridge
    external: true
  socketProxyNetwork:
    driver: bridge
    external: true
  guacamoleStackNetwork:
    driver: bridge
    external: true
  immichStackNetwork:
    driver: bridge
    external: true