version: "3.8"
services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    init: true
    volumes:
      - ${DOCKERCONFDIR}/authelia:/config
    ports:
      - 9091:9091
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    networks:
      - shyDockerServer

networks:
  shyDockerServer:
    driver: bridge
    external: true
