version: "3.8"
services:
  yacht:
    command: -H tcp://dockerproxy:2375
    container_name: yacht
    image: selfhostedpro/yacht
    environment:
      DOCKER_HOST: dockerproxy
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    ports:
      - 8000:8000
    networks:
      - shyDockerServer
    restart: unless-stopped
    labels:
      - swag=enable
      - swag_auth=authelia
    volumes:
      - ${DOCKERCONFDIR}/yacht:/config

networks:
  shyDockerServer:
    driver: bridge
    external: true