version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - arrStackNetwork
    - jellyStackNetwork

x-authelia-conf: &authelia
  labels:
    - swag=enable
    - swag_auth=authelia

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin-rffmpeg
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    ports:
      - 8096:8096
    volumes:
      - ${DOCKERCONFDIR}/jellyfin:/config
      - ${DOCKERCONFDIR}/jellyfin/config/cache:/config/cache:z
      - ${DOCKERCONFDIR}/jellyfin/config/data/transcodes:/config/transcodes:z
      - ${DOCKERCONFDIR}/jellyfin/config/data/data/subtitles:/config/data/subtitles:z
      - ${DOCKERSTORAGEDIR}/medialibrary/movies-anime:/data/anime_movies
      - ${DOCKERSTORAGEDIR}/medialibrary/movies:/data/movies
      - ${DOCKERSTORAGEDIR}/medialibrary/tv-anime:/data/anime_tvshows
      - ${DOCKERSTORAGEDIR}/medialibrary/tv:/data/tvshows
      - ${DOCKERCONFDIR}/jellyfin/rffmpeg:/etc/rffmpeg

  nfs-server:
    container_name: jellyfin_nfs_server
    image: ghcr.io/obeone/nfs-server:latest
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    environment:
      TZ: ${TZ}
      NFS_EXPORT_0: /config/cache           *(rw,sync,no_subtree_check,no_root_squash)
      NFS_EXPORT_1: /config/transcodes      *(rw,sync,no_subtree_check,no_root_squash)
      NFS_EXPORT_2: /config/data/subtitles  *(rw,sync,no_subtree_check,no_root_squash)
    <<: *default_conf
    ports:
      - 2049:2049
    volumes:
      - ${DOCKERCONFDIR}/jellyfin/config/cache:/config/cache:z
      - ${DOCKERCONFDIR}/jellyfin/config/data/transcodes:/config/transcodes:z
      - ${DOCKERCONFDIR}/jellyfin/config/data/data/subtitles:/config/data/subtitles:z
      - /lib/modules:/lib/modules:ro
    security_opt:
      - apparmor=erichough-nfs

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      <<: *environment
    <<: [*default_conf, *authelia]
    ports:
      - 5055:5055
    volumes:
      - ${DOCKERCONFDIR}/jellyseerr:/app/config

networks:
  jellyStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
