---

- HP SFF Monitoring:
    - CPU:
        widget:
            type: glances
            url: http://glances:61208
            version: 4 
            metric: cpu
    - Memory:
        widget:
            type: glances
            url: http://glances:61208
            version: 4 
            metric: memory
    - Network:
        widget:
            type: glances
            url: http://glances:61208
            version: 4 
            metric: network:eth0
    - Process:
        widget:
            type: glances
            url: http://glances:61208
            version: 4 
            metric: process

- T440p_1 Monitoring:
    - CPU:
        widget:
            type: glances
            url: http://192.168.1.8:61208
            version: 4 
            metric: cpu
    - Memory:
        widget:
            type: glances
            url: http://192.168.1.8:61208
            version: 4 
            metric: memory
    - Network:
        widget:
            type: glances
            url: http://192.168.1.8:61208
            version: 4 
            metric: network:eth0
    - Process:
        widget:
            type: glances
            url: http://192.168.1.8:61208
            version: 4 
            metric: process

- RD450 Monitoring:
    - CPU:
        widget:
            type: glances
            url: http://192.168.1.6:61208
            version: 4 
            metric: cpu
    - Memory:
        widget:
            type: glances
            url: http://192.168.1.6:61208
            version: 4 
            metric: memory
    - Network:
        widget:
            type: glances
            url: http://192.168.1.6:61208
            version: 4 
            metric: network:eth0
    - Process:
        widget:
            type: glances
            url: http://192.168.1.6:61208
            version: 4 
            metric: process

- Important stuff:
    - Proxmox:
        icon: proxmox.png
        href: https://proxmox.yabailocal.duckdns.org
        siteMonitor: https://proxmox.yabailocal.duckdns.org
        description: main Proxmox server
        widget:
            type: proxmox
            url: https://proxmox.yabailocal.duckdns.org
            username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"
    - Proxmox-RD450:
        icon: proxmox.png
        href: https://rd450-proxmox.yabailocal.duckdns.org
        siteMonitor: https://rd450-proxmox.yabailocal.duckdns.org
        description: thinkserver rd450 Proxmox server
        widget:
            type: proxmox
            url: https://rd450-proxmox.yabailocal.duckdns.org
            username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"
    - YabaiMediaVault:
        icon: openmediavault.png
        href: https://omv.yabailocal.duckdns.org
        siteMonitor: https://omv.yabailocal.duckdns.org
        description: NAS setup (services in widget)
        widget:
            type: openmediavault
            url: https://omv.yabailocal.duckdns.org
            username: "{{HOMEPAGE_VAR_OVM_USERNAME}}"
            password: "{{HOMEPAGE_VAR_OVM_PASSWORD}}"
            method: services.getStatus # required
    - Adguard Home:
        icon: adguard-home.png
        href: http://192.168.1.199
        siteMonitor: http://192.168.1.199
        description: Adblocker, DNS set in router
        widget:
            type: adguard
            url: http://192.168.1.199:80
            username: "{{HOMEPAGE_VAR_USER}}"
            password: "{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}"
    - Proxmox Backup Server:
        icon: proxmox-light.png
        href: https://pbs.yabailocal.duckdns.org
        siteMonitor: https://pbs.yabailocal.duckdns.org
        description: main PBS, running along main Proxmox
        # widget:
        #     type: proxmoxbackupserver
        #     url: https://192.168.1.13:8007
        #     username: "{{HOMEPAGE_VAR_PBS_USERNAME}}"
        #     password: "{{HOMEPAGE_VAR_PBS_PASSWORD}}"

- Docker services:
    - myspeed:
        icon: mdi-speedometer
        description: speedtest
        href: https://myspeed.yabailocal.duckdns.org
        server: hpsff-proxy
        container: myspeed
        widget:
            type: myspeed
            url: http://myspeed:5216
    - romm:
        icon: romm.png
        description: rom manager
        href: https://romm.yabailocal.duckdns.org
        server: rd450
        container: romm
        widget:
            type: romm
            url: https://romm.yabailocal.duckdns.org
            username: "{{HOMEPAGE_VAR_USER}}"
            password: "{{HOMEPAGE_VAR_ROMM_PWD}}"
    - qbittorrent:
        icon: qbittorrent.png
        description: torrent client
        href: https://qbittorrent.yabailocal.duckdns.org
        server: hpsff-proxy
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://qbittorrent:8080
            username: shyonae
            password: "{{HOMEPAGE_VAR_QBITTORRENT_PWD}}"
    - immich:
        icon: immich.png
        description: photos
        href: https://immich.yabailocal.duckdns.org
        server: hpsff-proxy
        container: immich_server
        widget:
            type: immich
            url: https://immich.yabailocal.duckdns.org
            key: "{{HOMEPAGE_VAR_IMMICH_TOKEN}}"
    - audiobookshelf:
        icon: audiobookshelf.png
        description: audiobooks / podcasts
        href: https://audiobookshelf.yabailocal.duckdns.org
        server: hpsff-proxy
        container: audiobookshelf
        widget:
            type: audiobookshelf
            url: http://audiobookshelf:80
            key: "{{HOMEPAGE_VAR_AUDIOBOOKSHELF_KEY}}"
    - bazarr:
        icon: bazarr.png
        description: subtitles
        href: https://bazarr.yabailocal.duckdns.org
        server: hpsff-proxy
        container: bazarr
        widget:
            type: bazarr
            url: http://bazarr:6767
            username: shyonae
            key: "{{HOMEPAGE_VAR_BAZARR_KEY}}"
    - radarr:
        icon: radarr.png
        description: movies
        href: https://radarr.yabailocal.duckdns.org
        server: hpsff-proxy
        container: radarr
        widget:
            type: radarr
            url: http://radarr:7878
            username: shyonae
            key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
    - sonarr:
        icon: sonarr.png
        description: tv shows
        href: https://sonarr.yabailocal.duckdns.org
        server: hpsff-proxy
        container: sonarr
        widget:
            type: sonarr
            url: http://sonarr:8989
            username: shyonae
            key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
    - readarr:
        icon: readarr.png
        description: books / audiobooks
        href: https://readarr.yabailocal.duckdns.org
        server: hpsff-proxy
        container: readarr
        widget:
            type: readarr
            url: http://readarr:8787
            key: "{{HOMEPAGE_VAR_READARR_KEY}}"
    - prowlarr:
        icon: prowlarr.png
        description: index manager
        href: https://prowlarr.yabailocal.duckdns.org
        server: hpsff-proxy
        container: prowlarr
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            username: shyonae
            key: "{{HOMEPAGE_VAR_PROWLARR_KEY}}"
    - jellyfin:
        icon: jellyfin.png
        description: streaming platform
        href: https://jellyfin.shyonaemediaserver.work
        server: hpsff-proxy
        container: jellyfin
        widget:
            type: jellyfin
            url: http://jellyfin:8096
            key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true
    - jellyseerr:
        icon: jellyseerr.png
        description: request stuff for jellyfin
        href: https://jellyseer.yabailocal.duckdns.org
        server: hpsff-proxy
        container: jellyseerr
        widget:
            type: jellyseerr
            url: http://jellyseerr:5055
            key: "{{HOMEPAGE_VAR_JELLYSEER_KEY}}"
    - navidrome:
        icon: navidrome.png
        description: music streaming
        href: https://navidrome.shyonaemediaserver.work
        server: hpsff-proxy
        container: navidrome
        widget:
            type: navidrome
            url: http://navidrome:4533
            user: shyonae
            token: "{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}" # md5(password + salt)
            salt: "{{HOMEPAGE_VAR_NAVIDROME_SALT}}"
    - linkwarden:
        icon: linkwarden.png
        description: bookmarks
        href: https://linkwarden.yabailocal.duckdns.org
        server: t440p_1
        container: linkwarden
        widget:
            type: linkwarden
            url: https://linkwarden.yabailocal.duckdns.org
            key: "{{HOMEPAGE_VAR_LINKWARDEN_TOKEN}}"
    - homebox:
        icon: homebox.png
        description: storage
        href: https://homebox.yabailocal.duckdns.org
        server: t440p_1
        container: homebox
        widget:
            type: homebox
            url: https://homebox.yabailocal.duckdns.org
            username: "{{HOMEPAGE_VAR_EMAIL}}"
            password: "{{HOMEPAGE_VAR_HOMEBOX_PWD}}"
    - nginx-proxy-manager:
        icon: nginx-proxy-manager.png
        description: https on local domains
        href: https://npm.yabailocal.duckdns.org
        server: t440p_1
        container: nginx-proxy-manager
        widget:
            type: npm
            url: https://npm.yabailocal.duckdns.org
            username: "{{HOMEPAGE_VAR_EMAIL}}"
            password: "{{HOMEPAGE_VAR_NPM_PWD}}"
    - shoko-server:
        icon: shoko.png
        description: anime manager
        href: https://shoko.yabailocal.duckdns.org
        server: rd450
        container: shokoserver
    - firefly:
        icon: mdi-cash
        description: finance manager
        href: https://firefly.yabailocal.duckdns.org
        server: hpsff-proxy
        container: firefly
    - it-tools:
        icon: it-tools.png
        description: very useful tools
        href: https://it-tools.yabailocal.duckdns.org
        server: t440p_1
        container: it-tools
    - stirling-pdf:
        icon: stirling-pdf.png
        description: pdf tools
        href: https://s-pdf.yabailocal.duckdns.org
        server: rd450
        container: s-pdf
    - manyfold:
        icon: manyfold.png
        description: stl files for 3d printing
        href: https://manyfold.yabailocal.duckdns.org
        server: rd450
        container: manyfold
    - notifiarr:
        icon: notifiarr.png
        description: TRaSH Guides updates for *arrs
        href: https://notifiarr.yabailocal.duckdns.org
        server: hpsff-proxy
        container: notifiarr
    - portainer:
        icon: portainer.png
        href: https://portainer.yabailocal.duckdns.org
        description: container management
        server: hpsff-proxy
        container: portainer
    - syncthing:
        icon: syncthing.png
        description: file sync
        href: https://syncthing.yabailocal.duckdns.org
        server: hpsff-proxy
        container: syncthing
    - wg-easy:
        icon: wireguard.png
        description: vpn
        href: https://wireguard.yabailocal.duckdns.org
        server: hpsff-proxy
        container: wg-easy
    - glances-hpsff:
        icon: glances.png
        description: monitoring
        href: https://glances.yabailocal.duckdns.org
        server: hpsff-proxy
        container: glances
    - glances-t440p1:
        icon: glances.png
        description: monitoring
        href: https://glances2.yabailocal.duckdns.org
        server: t440p_1
        container: glances
    - glances-rd450:
        icon: glances.png
        description: monitoring
        href: https://glances3.yabailocal.duckdns.org
        server: rd450
        container: glances
    - betanin:
        icon: beets.png
        description: based man-in-the-middle of your torrent client and music player
        href: https://betanin.yabailocal.duckdns.org
        server: hpsff-proxy
        container: betanin
    - betanin-move:
        icon: beets.png
        description: for deemix / tidarr downloads
        href: https://betaninm.yabailocal.duckdns.org
        server: hpsff-proxy
        container: betanin
    - deemix:
        icon: mdi-equalizer
        description: deezer downloader
        href: https://deemix.yabailocal.duckdns.org
        server: hpsff-proxy
        container: deemix
    - tidarr:
        icon: si-tidal
        description: tidal downloader
        href: https://tidarr.yabailocal.duckdns.org
        server: hpsff-proxy
        container: tidarr
    - flaresolverr: 
        icon: flaresolverr.png
        description: proxy server for *arrs
        server: hpsff-proxy
        container: flaresolverr
    - hoyolab-auto: 
        icon: mdi-clipboard-check
        description: daily check-in
        server: hpsff-proxy
        container: hoyolab-auto
    - unpackerr: 
        icon: mdi-package-variant
        description: download extractor
        server: hpsff-proxy
        container: unpackerr
    - dockerproxy-main-hpsff:
        icon: mdi-arrow-decision
        description: docker socket proxy
        server: hpsff-proxy
        container: dockerproxy
    - dockerproxy-t440p1:
        icon: mdi-arrow-decision
        description: docker socket proxy
        server: t440p_1
        container: dockerproxy
    - dockerproxy-rd450:
        icon: mdi-arrow-decision
        description: docker socket proxy
        server: rd450
        container: dockerproxy
    - swag:
        icon: linuxserver-io.png
        description: Main reverse proxy
        server: hpsff-proxy
        container: swag
    - swag_duckdns:
        icon: linuxserver-io.png
        description: reverse proxy for wireguard
        server: hpsff-proxy
        container: swag_duckdns
    - immich_redis:
        icon: redis.png
        description: redis for immich
        server: rd450
        container: immich_redis
    - immich_postgres:
        icon: postgres.png
        description: postgres for immich
        server: rd450
        container: immich_postgres
    - linkwarden_database:
        icon: postgres.png
        description: db for linkwarden
        server: t440p_1
        container: linkwarden_postgres_db
    - romm_database:
        icon: mariadb.png
        description: db for romm
        server: rd450
        container: romm_db
    - crowdsec:
        icon: crowdsec.png
        description: blocklist for swag
        server: hpsff-proxy
        container: crowdsec
    - duckdns:
        icon: duckdns.png
        description: dynamic dns for wireguard
        server: hpsff-proxy
        container: duckdns
    - authelia:
        icon: authelia.png
        description: authentication for swag
        server: hpsff-proxy
        container: authelia
    - redis:
        icon: redis.png
        description: in-memory database
        server: hpsff-proxy
        container: redis
    - cloudflare-ddns:
        icon: cloudflare.png
        description: update cloudflare tunnels for swag
        server: hpsff-proxy
        container: cloudflare-ddns
    - docker-volume-backup-hpsff:
        icon: si-docker
        description: backup specific containers to smb share
        server: hpsff-proxy
        container: docker-volume-backup
    - docker-volume-backup-t440p_1:
        icon: si-docker
        description: backup specific containers to smb share
        server: t440p_1
        container: docker-volume-backup
    - docker-volume-backup-rd450:
        icon: si-docker
        description: backup specific containers to smb share
        server: rd450
        container: docker-volume-backup