---

- HP SFF Monitoring:
    - CPU:
        widget:
            type: glances
            url: http://glances:61208
            version: 4 
            metric: cpu
    - Memory:
        widget:
            type: glances
            url: http://glances:61208
            version: 4 
            metric: memory
    - Network:
        widget:
            type: glances
            url: http://glances:61208
            version: 4 
            metric: network:eth0
    - Process:
        widget:
            type: glances
            url: http://glances:61208
            version: 4 
            metric: process

- T440p_1 Monitoring:
    - CPU:
        widget:
            type: glances
            url: http://192.168.1.8:61208
            version: 4 
            metric: cpu
    - Memory:
        widget:
            type: glances
            url: http://192.168.1.8:61208
            version: 4 
            metric: memory
    - Network:
        widget:
            type: glances
            url: http://192.168.1.8:61208
            version: 4 
            metric: network:eth0
    - Process:
        widget:
            type: glances
            url: http://192.168.1.8:61208
            version: 4 
            metric: process

- Important stuff:
    - Proxmox:
        icon: proxmox.png
        href: https://192.168.1.123:8006
        siteMonitor: https://192.168.1.123:8006
        description: main Proxmox server
        widget:
            type: proxmox
            url: https://192.168.1.123:8006
            username: "{{HOMEPAGE_VAR_PROXMOX_USERNAME}}"
            password: "{{HOMEPAGE_VAR_PROXMOX_PASSWORD}}"
    - Proxmox Backup Server:
        icon: proxmox-light.png
        href: https://192.168.1.13:8007
        ping: https://192.168.1.13:8007
        description: main PBS, running along main Proxmox
        # widget:
        #     type: proxmoxbackupserver
        #     url: https://192.168.1.13:8007
        #     username: "{{HOMEPAGE_VAR_PBS_USERNAME}}"
        #     password: "{{HOMEPAGE_VAR_PBS_PASSWORD}}"
    - YabaiMediaVault:
        icon: openmediavault.png
        href: http://192.168.1.12
        siteMonitor: http://192.168.1.12
        description: NAS setup (services in widget)
        widget:
            type: openmediavault
            url: http://192.168.1.12
            username: "{{HOMEPAGE_VAR_OVM_USERNAME}}"
            password: "{{HOMEPAGE_VAR_OVM_PASSWORD}}"
            method: services.getStatus # required
    - Adguard Home:
        icon: adguard-home.png
        href: http://192.168.1.199
        siteMonitor: http://192.168.1.199
        description: Adblocker, DNS set in router
        widget:
            type: adguard
            url: http://192.168.1.199:80
            username: "{{HOMEPAGE_VAR_ADGUARD_USERNAME}}"
            password: "{{HOMEPAGE_VAR_ADGUARD_PASSWORD}}"


- Docker services:
    - myspeed:
        icon: mdi-speedometer
        description: speedtest
        href: http://192.168.1.9:5216
        server: hpsff-proxy
        container: myspeed
        widget:
            type: myspeed
            url: http://myspeed:5216
    - navidrome:
        icon: navidrome.png
        description: music streaming
        href: http://192.168.1.9:4533
        server: hpsff-proxy
        container: navidrome
        widget:
            type: navidrome
            url: http://navidrome:4533
            user: shyonae
            token: "{{HOMEPAGE_VAR_NAVIDROME_TOKEN}}" # md5(password + salt)
            salt: "{{HOMEPAGE_VAR_NAVIDROME_SALT}}"
    - qbittorrent:
        icon: qbittorrent.png
        description: torrent client
        href: http://192.168.1.9:8080
        server: hpsff-proxy
        container: qbittorrent
        widget:
            type: qbittorrent
            url: http://qbittorrent:8080
            username: shyonae
            password: "{{HOMEPAGE_VAR_QBITTORRENT_PWD}}"
    - linkwarden:
        icon: linkwarden.png
        description: bookmarks
        href: http://192.168.1.8:3007
        # widget:
        #     type: linkwarden
        #     url: http://192.168.1.8:3007
        #     key: "{{HOMEPAGE_VAR_LINKWARDEN_TOKEN}}" # idk why I can't copy the token
    - bazarr:
        icon: bazarr.png
        description: subtitles
        href: http://192.168.1.9:6767
        server: hpsff-proxy
        container: bazarr
        widget:
            type: bazarr
            url: http://bazarr:6767
            username: shyonae
            key: "{{HOMEPAGE_VAR_BAZARR_KEY}}"
    - radarr:
        icon: radarr.png
        description: movies
        href: http://192.168.1.9:7878
        server: hpsff-proxy
        container: radarr
        widget:
            type: radarr
            url: http://radarr:7878
            username: shyonae
            key: "{{HOMEPAGE_VAR_RADARR_KEY}}"
    - sonarr:
        icon: sonarr.png
        description: tv shows
        href: http://192.168.1.9:8989
        server: hpsff-proxy
        container: sonarr
        widget:
            type: sonarr
            url: http://sonarr:8989
            username: shyonae
            key: "{{HOMEPAGE_VAR_SONARR_KEY}}"
    - prowlarr:
        icon: prowlarr.png
        description: index manager
        href: http://192.168.1.9:9696
        server: hpsff-proxy
        container: prowlarr
        widget:
            type: prowlarr
            url: http://prowlarr:9696
            username: shyonae
            key: "{{HOMEPAGE_VAR_PROWLARR_KEY}}"
    - jellyfin:
        icon: jellyfin.png
        description: streaming platform
        href: https://jellyfin.shyonaemediaserver.work
        server: hpsff-proxy
        container: jellyfin
        widget:
            type: jellyfin
            url: http://jellyfin:8096
            key: "{{HOMEPAGE_VAR_JELLYFIN_KEY}}"
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true
    - jellyseerr:
        icon: jellyseerr.png
        description: request stuff for jellyfin
        href: http://192.168.1.9:5055
        server: hpsff-proxy
        container: jellyseerr
        widget:
            type: jellyseerr
            url: http://jellyseerr:5055
            key: "{{HOMEPAGE_VAR_JELLYSEER_KEY}}"
    - notifiarr:
        icon: notifiarr.png
        description: TRaSH Guides updates for *arrs
        href: http://192.168.1.9:5454
        server: hpsff-proxy
        container: notifiarr
    - portainer:
        icon: portainer.png
        href: http://192.168.1.9:9000
        description: container management
        server: hpsff-proxy
        container: portainer
    - glances:
        icon: glances.png
        description: monitoring
        href: http://192.168.1.9:61208
        server: hpsff-proxy
        container: glances
    - betanin:
        icon: beets.png
        description: based man-in-the-middle of your torrent client and music player
        href: http://192.168.1.9:9393
        server: hpsff-proxy
        container: betanin
    - flaresolverr: 
        icon: flaresolverr.png
        description: proxy server for *arrs
        server: hpsff-proxy
        container: flaresolverr
    - unpackerr: 
        icon: mdi-package-variant
        description: download extractor
        server: hpsff-proxy
        container: unpackerr
    - dockerproxy:
        icon: mdi-arrow-decision
        description: docker socket proxy
        server: hpsff-proxy
        container: dockerproxy
    - swag:
        icon: linuxserver-io.png
        description: Main reverse proxy
        server: hpsff-proxy
        container: swag
    - crowdsec:
        icon: crowdsec.png
        description: blocklist for swag
        server: hpsff-proxy
        container: crowdsec
    - authelia:
        icon: authelia.png
        description: authentication for swag
        server: hpsff-proxy
        container: authelia
    - redis:
        icon: redis.png
        description: in-memory database
        server: hpsff-proxy
        container: redis
    - cloudflare-ddns:
        icon: cloudflare.png
        description: update cloudflare tunnels for swag
        server: hpsff-proxy
        container: cloudflare-ddns
    - docker-volume-backup:
        icon: si-docker
        description: backup specific containers to smb share
        server: hpsff-proxy
        container: docker-volume-backup