global:
  checkNewVersion: false
  sendAnonymousUsage: false
logs:
  level: DEBUG
log:
  filePath: "/tmp/log.txt"
  format: json
  level: DEBUG
api:
  dashboard: true
  insecure: true
providers:
  docker:
    exposedByDefault: false
entryPoints:
  web:
    address: :80
  websecure:
    address: :443