version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - infisicalNetwork

x-authelia-conf: &labels
  labels:
    - docker-volume-backup.stop-during-backup=true

services:
  infisical-db-migration:
    container_name: infisical-db-migration
    image: infisical/infisical:latest-postgres
    env_file: ../../../appdata/infisical/.env
    depends_on:
      - infisical_db
    <<: [*default_conf, *labels]
    command: npm run migration:latest
    pull_policy: always

  infisical-backend:
    container_name: infisical-backend
    image: infisical/infisical:latest-postgres
    env_file: ../../../appdata/infisical/.env
    depends_on:
      - infisical_db
      - infisical-redis
      - infisical-db-migration
    <<: [*default_conf, *labels]
    pull_policy: always
    ports:
      - 8097:8080
    environment:
      - NODE_ENV=production

  infisical-redis:
    container_name: infisical-redis
    image: redis
    env_file: ../../../appdata/infisical/.env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    <<: [*default_conf, *labels]
    volumes:
      - ${DOCKERCONFDIR}/infisical/redis_data:/data

  infisical_db:
    container_name: infisical_db
    hostname: infisical_db
    image: postgres:14-alpine
    env_file: ../../../appdata/infisical/.env
    <<: [*default_conf, *labels]
    volumes:
      - ${DOCKERCONFDIR}/infisical/pg_data:/var/lib/postgresql/data

networks:
  infisicalNetwork:
    driver: bridge
    external: true
