version: "3.8"
services:
  sonarranime:
    container_name: sonarranime
    image: lscr.io/linuxserver/sonarr:develop
    ports:
      - 8990:8989
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    networks:
      - shyDockerServer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/sonarranime:/config
      - ${DOCKERSTORAGEDIR}:/storage

networks:
  shyDockerServer:
    driver: bridge
    external: true
