services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      - "8088:8080"
    restart: unless-stopped
    labels:
      - docker-volume-backup.stop-during-backup=true
    networks:
      - reverseProxyNetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config.traefik.yaml:/etc/traefik/traefil.yaml:ro
      - ${DOCKERCONFDIR}/traefik/log.txt:/tmp/log.txt

networks:
  reverseProxyNetwork:
    driver: bridge
    external: true