version: "3.8"
services:
  portainer:
    command: -H tcp://dockerproxy:2375
    container_name: portainer
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      DOCKER_HOST: dockerproxy
    image: portainer/portainer-ce:latest
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    networks:
      - shyDockerServer
    ports:
      - 9000:9000
    labels:
      - swag=enable
      - swag_auth=authelia
    restart: unless-stopped
    volumes:
      - ${DOCKERCONFDIR}/portainer:/data
      - ${DOCKERSTORAGEDIR}:/storage

networks:
  shyDockerServer:
    driver: bridge
    external: true
