version: "3.8"
services:
  prowlarr:
    container_name: prowlarr
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: lscr.io/linuxserver/prowlarr:latest
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    ports:
      - 9696:9696
    networks:
      - shyDockerServer
    labels:
      - swag=enable
      - swag_auth=authelia
    restart: unless-stopped
    volumes:
      - ${DOCKERCONFDIR}/prowlarr:/config

networks:
  shyDockerServer:
    driver: bridge
    external: true
