version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - musicStackNetwork
  labels:
    - docker-volume-backup.stop-during-backup=true

services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    user: ${PUID}:${PGID}
    <<: *default_conf
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_LASTFM_APIKEY: ${ND_LASTFM_APIKEY}
      ND_LASTFM_SECRET: ${ND_LASTFM_SECRET}
      ND_SPOTIFY_ID: ${ND_SPOTIFY_ID}
      ND_SPOTIFY_SECRET: ${ND_SPOTIFY_SECRET}
    ports:
      - "4533:4533"
    volumes:
      - ${DOCKERCONFDIR}/navidrome:/data
      - ${DOCKERSTORAGEDIR}/medialibrary/music:/music:ro

  beets:
    container_name: beets
    image: lscr.io/linuxserver/beets:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8337:8337
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/beets:/config
      - ${DOCKERSTORAGEDIR}/medialibrary/music:/music
      - ${DOCKERSTORAGEDIR}/downloads/torrents/music:/downloads

  betanin:
    image: sentriz/betanin:latest
    container_name: betanin
    ports:
      - 9393:9393
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/betanin/data:/b/.local/share/betanin/
      - ${DOCKERCONFDIR}/betanin/config:/b/.config/betanin/
      - ${DOCKERCONFDIR}/betanin/beets:/b/.config/beets
      - ${DOCKERSTORAGEDIR}/medialibrary/music:/music/
      - ${DOCKERSTORAGEDIR}:/storage

networks:
  musicStackNetwork:
    driver: bridge
    external: true
