version: "3.8"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      URL: ${SWAG_URL}
      SUBDOMAINS: wildcard
      VALIDATION: dns
      CERTPROVIDER: zerossl
      DNSPLUGIN: cloudflare
      STAGING: false
      PROPAGATION: 30
      EMAIL: ${DEFAULT_EMAIL}
      DOCKER_MODS: linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy|linuxserver/mods:universal-cloudflared|linuxserver/mods:swag-crowdsec|linuxserver/mods:swag-auto-reload
      CROWDSEC_API_KEY: ${SWAG_CROWDSEC_API_KEY}
      CROWDSEC_LAPI_URL: http://crowdsec:8080
      DOCKER_HOST: dockerproxy
      CF_ZONE_ID: ${SWAG_CF_ZONE_ID}
      CF_ACCOUNT_ID: ${SWAG_CF_ACCOUNT_ID}
      CF_API_TOKEN: ${SWAG_CF_API_TOKEN}
      CF_TUNNEL_NAME: ${SWAG_CF_TUNNEL_NAME}
      CF_TUNNEL_PASSWORD=: ${SWAG_CF_TUNNEL_PASSWORD}
      FILE__CF_TUNNEL_CONFIG: /config/tunnelconfig.yml
    networks:
      - shyDockerServer
    ports:
      - 443:443
    extra_hosts:
      - ${SWAG_EXTRA_HOSTS}
    volumes:
      - ${DOCKERCONFDIR}/swag:/config
    restart: unless-stopped

networks:
  shyDockerServer:
    driver: bridge
    external: true
