version: "3.8"

x-default-conf: &default_conf
  user: "${PUID}:${PGID}"
  restart: unless-stopped
  networks:
    - generalStackNetwork

services:
  postgres:
    image: postgres:16-alpine
    container_name: linkwarden_postgres_db
    environment:
      POSTGRES_PASSWORD: ${LINKWARDEN_DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: linkwarden_postgres_db
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/linkwarden/postgresql:/var/lib/postgresql/data

  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    environment:
      - NEXTAUTH_SECRET=${LINKWARDEN_NEXTAUTH_SECRET}
      - NEXTAUTH_URL=http://localhost:3000
      - DATABASE_URL=postgresql://postgres:${LINKWARDEN_DB_PASSWORD}@linkwarden_postgres_db:5432/postgres
    <<: *default_conf
    ports:
      - 3000:3000
    volumes:
      - ${DOCKERCONFDIR}/linkwarden/data:/data/data
    depends_on:
      - postgres
