version: "3.8"
services:
  bazarranime:
    container_name: bazarranime
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - 6768:6767
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    networks:
      - shyDockerServer
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/bazarranime:/config
      - ${DOCKERSTORAGEDIR}:/storage

networks:
  shyDockerServer:
    driver: bridge
    external: true
