version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - swagStackNetwork

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      <<: *environment
    <<: *default_conf
    labels:
      - swag=enable
    ports:
      - 9091:9091
    volumes:
      - authelia:/config

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    depends_on:
      - authelia
      - crowdsec
      - cloudflare-ddns
    cap_add:
      - NET_ADMIN
    environment:
      <<: *environment
      URL: ${SWAG_URL}
      SUBDOMAINS: wildcard
      VALIDATION: dns
      CERTPROVIDER: zerossl
      DNSPLUGIN: cloudflare
      STAGING: false
      PROPAGATION: 30
      EMAIL: ${DEFAULT_EMAIL}
      DOCKER_MODS: linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy|linuxserver/mods:universal-cloudflared|linuxserver/mods:swag-crowdsec|linuxserver/mods:swag-auto-reload|linuxserver/mods:swag-dashboard
      CROWDSEC_API_KEY: ${SWAG_CROWDSEC_API_KEY}
      CROWDSEC_LAPI_URL: http://crowdsec:8080
      DOCKER_HOST: dockerproxy
      CF_ZONE_ID: ${SWAG_CF_ZONE_ID}
      CF_ACCOUNT_ID: ${SWAG_CF_ACCOUNT_ID}
      CF_API_TOKEN: ${SWAG_CF_API_TOKEN}
      CF_TUNNEL_NAME: ${SWAG_CF_TUNNEL_NAME}
      CF_TUNNEL_PASSWORD=: ${SWAG_CF_TUNNEL_PASSWORD}
      FILE__CF_TUNNEL_CONFIG: /config/tunnelconfig.yml
    restart: unless-stopped
    networks:
      - swagStackNetwork
      - managementStackNetwork
      - arrStackNetwork
      - downloadStackNetwork
      - generalStackNetwork
      - socketProxyNetwork
      - guacamoleStackNetwork
    ports:
      - 443:443
    volumes:
      - swag:/config
    extra_hosts:
      - ${SWAG_EXTRA_HOSTS}

  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      <<: *environment
      COLLECTIONS: "crowdsecurity/nginx crowdsecurity/http-cve crowdsecurity/whitelist-good-actors"
      CUSTOM_HOSTNAME: ${CROWDSEC_CUSTOM_HOSTNAME}
    <<: *default_conf
    volumes:
      - crowdsec/config:/etc/crowdsec:rw
      - crowdsec/data:/var/lib/crowdsec/data:rw
      - swag/log/nginx:/var/log/swag:ro
      - /var/log:/var/log/host:ro
    security_opt:
      - no-new-privileges=true

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *environment
    <<: *default_conf
    volumes:
      - cloudflare-ddns/config.json:/config.json

volumes:
  cloudflare-ddns:
    name: cloudflare-ddns
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/cloudflare-ddns
  crowdsec:
    name: cloudflare
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/crowdsec
  swag:
    name: swag
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/swag
  authelia:
    name: authelia
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/authelia

networks:
  swagStackNetwork:
    driver: bridge
    external: true
  managementStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
  downloadStackNetwork:
    driver: bridge
    external: true
  generalStackNetwork:
    driver: bridge
    external: true
  socketProxyNetwork:
    driver: bridge
    external: true
  guacamoleStackNetwork:
    driver: bridge
    external: true
