version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - swagStackNetwork

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      <<: *environment
    <<: *default_conf
    ports:
      - 9091:9091
    volumes:
      - ${DOCKERCONFDIR}/authelia:/config

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      <<: *environment
      URL: ${SWAG_URL}
      SUBDOMAINS: wildcard
      VALIDATION: dns
      CERTPROVIDER: zerossl
      DNSPLUGIN: cloudflare
      STAGING: false
      PROPAGATION: 30
      EMAIL: ${DEFAULT_EMAIL}
      DOCKER_MODS: linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy|linuxserver/mods:universal-cloudflared|linuxserver/mods:swag-crowdsec|linuxserver/mods:swag-auto-reload
      CROWDSEC_API_KEY: ${SWAG_CROWDSEC_API_KEY}
      CROWDSEC_LAPI_URL: http://crowdsec:8080
      DOCKER_HOST: dockerproxy
      CF_ZONE_ID: ${SWAG_CF_ZONE_ID}
      CF_ACCOUNT_ID: ${SWAG_CF_ACCOUNT_ID}
      CF_API_TOKEN: ${SWAG_CF_API_TOKEN}
      CF_TUNNEL_NAME: ${SWAG_CF_TUNNEL_NAME}
      CF_TUNNEL_PASSWORD=: ${SWAG_CF_TUNNEL_PASSWORD}
      FILE__CF_TUNNEL_CONFIG: /config/tunnelconfig.yml
    restart: unless-stopped
    networks:
      - swagStackNetwork
      - managementStackNetwork
      - arrStackNetwork
      - downloadStackNetwork
      - generalStackNetwork
      - socketProxyNetwork
      - vaultNetwork
      - headscaleNetwork
    ports:
      - 443:443
    volumes:
      - ${DOCKERCONFDIR}/swag:/config
    extra_hosts:
      - ${SWAG_EXTRA_HOSTS}

  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      <<: *environment
      COLLECTIONS: "crowdsecurity/nginx crowdsecurity/http-cve crowdsecurity/whitelist-good-actors"
      CUSTOM_HOSTNAME: ${CROWDSEC_CUSTOM_HOSTNAME}
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/crowdsec/config:/etc/crowdsec:rw
      - ${DOCKERCONFDIR}/crowdsec/data:/var/lib/crowdsec/data:rw
      - ${DOCKERCONFDIR}/swag/log/nginx:/var/log/swag:ro
      - /var/log:/var/log/host:ro
    security_opt:
      - no-new-privileges=true

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *environment
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/cloudflare-ddns/config.json:/config.json

networks:
  swagStackNetwork:
    driver: bridge
    external: true
  managementStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
  downloadStackNetwork:
    driver: bridge
    external: true
  generalStackNetwork:
    driver: bridge
    external: true
  socketProxyNetwork:
    driver: bridge
    external: true
  vaultNetwork:
    driver: bridge
    external: true
  headscaleNetwork:
    driver: bridge
    external: true
