version: "3.8"

x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - swagStackNetwork

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    environment:
      <<: *environment
    <<: *default_conf
    labels:
      - swag=enable
    ports:
      - 9091:9091
    volumes:
      - ${DOCKERCONFDIR}/authelia:/config

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      <<: *environment
      URL: ${SWAG_URL}
      SUBDOMAINS: wildcard
      VALIDATION: dns
      CERTPROVIDER: zerossl
      DNSPLUGIN: cloudflare
      STAGING: false
      PROPAGATION: 30
      EMAIL: ${DEFAULT_EMAIL}
      DOCKER_MODS: linuxserver/mods:universal-docker|linuxserver/mods:swag-auto-proxy|linuxserver/mods:universal-cloudflared|linuxserver/mods:swag-crowdsec|linuxserver/mods:swag-auto-reload
      CROWDSEC_API_KEY: ${SWAG_CROWDSEC_API_KEY}
      CROWDSEC_LAPI_URL: http://crowdsec:8080
      DOCKER_HOST: dockerproxy
      CF_ZONE_ID: ${SWAG_CF_ZONE_ID}
      CF_ACCOUNT_ID: ${SWAG_CF_ACCOUNT_ID}
      CF_API_TOKEN: ${SWAG_CF_API_TOKEN}
      CF_TUNNEL_NAME: ${SWAG_CF_TUNNEL_NAME}
      CF_TUNNEL_PASSWORD=: ${SWAG_CF_TUNNEL_PASSWORD}
      FILE__CF_TUNNEL_CONFIG: /config/tunnelconfig.yml
    restart: unless-stopped
    networks:
      - swagStackNetwork
      - managementStackNetwork
      - arrStackNetwork
      - downloadStackNetwork
      - generalStackNetwork
      - socketProxyNetwork
      - guacamoleStackNetwork
    ports:
      - 443:443
    volumes:
      - ${DOCKERCONFDIR}/swag:/config
    extra_hosts:
      - ${SWAG_EXTRA_HOSTS}

  crowdsec:
    image: docker.io/crowdsecurity/crowdsec:latest
    container_name: crowdsec
    environment:
      <<: *environment
      COLLECTIONS: "crowdsecurity/nginx crowdsecurity/http-cve crowdsecurity/whitelist-good-actors"
      CUSTOM_HOSTNAME: ${CROWDSEC_CUSTOM_HOSTNAME}
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/crowdsec/config:/etc/crowdsec:rw
      - ${DOCKERCONFDIR}/crowdsec/data:/var/lib/crowdsec/data:rw
      - ${DOCKERCONFDIR}/swag/log/nginx:/var/log/swag:ro
      - /var/log:/var/log/host:ro
    security_opt:
      - no-new-privileges=true

  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    environment:
      <<: *environment
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/cloudflare-ddns/config.json:/config.json

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      <<: *environment
      SUBDOMAINS: ${DUCKDNS_SUBDOMAIN}
      TOKEN: ${DUCKDNS_TOKEN}
    <<: *default_conf

  swag_duckdns:
    image: lscr.io/linuxserver/swag
    container_name: swag_duckdns
    cap_add:
      - NET_ADMIN
    environment:
      <<: *environment
      DOCKER_MODS: linuxserver/mods:universal-docker|linuxserver/mods:swag-crowdsec
      CROWDSEC_API_KEY: ${SWAG_CROWDSEC_API_KEY}
      CROWDSEC_LAPI_URL: http://crowdsec:8080
      URL: ${DUCKDNS_SUBDOMAIN}
      SUBDOMAINS: wildcard
      VALIDATION: duckdns
      DUCKDNSTOKEN: ${DUCKDNS_TOKEN}
    <<: *default_conf
    volumes:
      - ${DOCKERCONFDIR}/swag_duckdns:/config

  wg-easy:
    image: weejewel/wg-easy
    container_name: wg-easy
    environment:
      WG_HOST: ${DUCKDNS_SUBDOMAIN}
      PASSWORD: ${WGEASY_PASSWORD}
      WG_DEFAULT_DNS: 1.1.1.1, 8.8.8.8, 8.8.4.4
    networks:
      - swagStackNetwork
      - managementStackNetwork
      - arrStackNetwork
      - downloadStackNetwork
      - generalStackNetwork
      - socketProxyNetwork
      - guacamoleStackNetwork
    volumes:
      - ${DOCKERCONFDIR}/wg-easy:/etc/wireguard
    restart: unless-stopped
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  wgui:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    user: "${PUID}:${PGID}"
    cap_add:
      - NET_ADMIN
    environment:
      SESSION_SECRET: ${WGEASY_PASSWORD}
      WGUI_USERNAME: shyonae
      WGUI_PASSWORD: test
      WGUI_ENDPOINT_ADDRESS: ${DUCKDNS_SUBDOMAIN}
      WG_CONF_TEMPLATE: /etc/wireguard/wg0_custom.conf
      WGUI_MANAGE_START: false
      WGUI_MANAGE_RESTART: false
    volumes:
      - ${DOCKERCONFDIR}/wgui/db:/app/db
      - ${DOCKERCONFDIR}/wgui/etc/wireguard:/etc/wireguard
    restart: unless-stopped
    networks:
      - swagStackNetwork
      - managementStackNetwork
      - arrStackNetwork
      - downloadStackNetwork
      - generalStackNetwork
      - socketProxyNetwork
      - guacamoleStackNetwork

networks:
  swagStackNetwork:
    driver: bridge
    external: true
  managementStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
  downloadStackNetwork:
    driver: bridge
    external: true
  generalStackNetwork:
    driver: bridge
    external: true
  socketProxyNetwork:
    driver: bridge
    external: true
  guacamoleStackNetwork:
    driver: bridge
    external: true
