version: "3.8"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      UMASK: ${UMASK}
      TZ: ${TZ}
    labels:
      - swag=enable
      - swag_auth=authentik
      - docker-volume-backup.stop-during-backup=true
      - "com.centurylinklabs.watchtower.monitor-only=true"
    networks:
      - downloadStackNetwork
      - arrStackNetwork
      - musicStackNetwork
    volumes:
      - ${DOCKERCONFDIR}/qbittorrent:/config
      - ${DOCKERSTORAGEDIR}:/storage
    ports:
      - 8080:8080
    restart: unless-stopped

networks:
  downloadStackNetwork:
    driver: bridge
    external: true
  musicStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
