version: "3.8"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:4.5.5
    container_name: qbittorrent
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      UMASK: ${UMASK}
      TZ: ${TZ}
    labels:
      - swag=enable
      - swag_auth=authelia
    networks:
      - downloadStackNetwork
      - arrStackNetwork
    volumes:
      - qbittorrent:/config
      - ${DOCKERSTORAGEDIR}:/storage
    ports:
      - 8080:8080
    restart: unless-stopped

volumes:
  qbittorrent:
    name: qbittorrent
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/media/docker-server/appdata/qbittorrent

networks:
  downloadStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
