version: "3"
services:
  actual_budget:
    image: actualbudget/actual-server:latest
    container_name: actual_budget
    user: "${PUID}:${PGID}"
    environment:
      TZ: ${TZ}
    volumes:
      - ${DOCKERCONFDIR}/actual_budget:/data
    restart: unless-stopped
    ports:
      - "5006:5006"
    networks:
      - generalStackNetwork

networks:
  generalStackNetwork:
    driver: bridge
    external: true
