version: "3.8"
services:
  flaresolverr:
    container_name: flaresolverr
    environment:
      CAPTCHA_SOLVER: none
      LOG_HTML: false
      LOG_LEVEL: info
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    image: ghcr.io/flaresolverr/flaresolverr:latest
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    networks:
      - shyDockerServer
    ports:
      - 8191:8191
    restart: unless-stopped

networks:
  shyDockerServer:
    driver: bridge
    external: true
