version: "3.8"
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - /${DOCKERCONFDIR}/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
    networks:
      - shyDockerServer

networks:
  shyDockerServer:
    driver: bridge
    external: true
