x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - generalStackNetwork
  logging:
    driver: "json-file"
    options:
      max-file: "2"
      max-size: "100m"

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    environment:
      <<: *environment
    <<: *default_conf
    labels:
      - docker-volume-backup.stop-during-backup=true
    ports:
      - 13378:80
    volumes:
      - ${DOCKERSTORAGEDIR}/medialibrary/books:/audiobooks
      - ${DOCKERSTORAGEDIR}/medialibrary/podcasts:/podcasts
      - ${DOCKERCONFDIR}/audiobookshelf/config:/config
      - ${DOCKERCONFDIR}/audiobookshelf/metadata:/metadata

networks:
  generalStackNetwork:
    driver: bridge
    external: true
