x-default-conf: &default_conf
  restart: unless-stopped
  networks:
    - arrStackNetwork
    - jellyStackNetwork
  logging:
    driver: "json-file"
    options:
      max-file: "2"
      max-size: "100m"

x-authelia-conf: &autheliaPlusBackup
  labels:
    - swag=enable
    - swag_auth=authelia
    - docker-volume-backup.stop-during-backup=true

x-environment: &environment
  PGID: ${PGID}
  PUID: ${PUID}
  TZ: ${TZ}

services:
  jellyfin:
    container_name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    group_add:
      - 303 # getent group render | cut -d: -f3
    environment:
      <<: *environment
    <<: [*default_conf, *autheliaPlusBackup]
    ports:
      - 8096:8096
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128 # hardware accel
    volumes:
      - ${DOCKERCONFDIR}/jellyfin:/config
      - ${DOCKERSTORAGEDIR}/medialibrary:/data

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      <<: *environment
    <<: [*default_conf, *autheliaPlusBackup]
    ports:
      - 5055:5055
    volumes:
      - ${DOCKERCONFDIR}/jellyseerr:/app/config

networks:
  jellyStackNetwork:
    driver: bridge
    external: true
  arrStackNetwork:
    driver: bridge
    external: true
