version: "3.8"
services:
  jellyseerr:
    image: fallenbagel/jellyseerr:1.5.0
    container_name: jellyseerr
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    labels:
      - swag=enable
      - swag_auth=authelia
    ports:
      - 5055:5055
    networks:
      - shyDockerServer
    volumes:
      - ${DOCKERCONFDIR}/jellyseerr:/app/config
    restart: unless-stopped

networks:
  shyDockerServer:
    driver: bridge
    external: true
